name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"

      - name: Install dependencies
        run: npm ci
      
      # - name: Format check
      #   run: npm run format:check

      - name: Run tests
        run: npm run test -- --coverage 
        env:
          CI: true