name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:

#   print: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print ref
#         env:
#           REPO: ${{ github.action_repository }}
#         run: |
#           echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node version (16.x)
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      # - name: Check formatting
      #   run: npm run format:check

      # - name: Run tests
      #   run: npm run test -- --coverage
      #   env:
      #     CI: true

      - name: Print diff
        run: git log --pretty=format:%s master..${{ SHA }}
        env: 
          SHA: ${{ github.sha }}

      - name: Send message to Slack \#general
        uses: "Ilshidur/action-slack@2.1.0"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          VERSION: ${{ steps.get-next-version.outputs.new-release-version }}
          RELEASE_URL: ${{ format('https://github.com/{0}/releases/tag/v{1}', github.repository, steps.get-next-version.outputs.new-release-version) }}
          # RELEASE_URL: ${{ format('{0}{1}', 'https://github.com/yuliankarapetkov/react-cicd/releases/tag/v', steps.get-next-version.outputs.new-release-version) }}
          SLACK_CUSTOM_PAYLOAD: '{ "text": "Hello" }'
