name: CI
on:
  pull_request:
    branches:
      - develop
      - staging
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Comment
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node version (16.x)
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --coverage
        env:
          CI: true
