name: CI
on:
  push:
    branches: [develop, master, fix-this]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo ${GITHUB_ACTION}

      # - name: Checkout branch
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Print diff
      #   env: 
      #     SHA: ${{ github.sha }}
      #   run: |
      #     git log --pretty=format:%s origin/master..origin/${GITHUB_HEAD_REF}

      # - name: Setup Node version (16.x)
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "16.x"

      # - name: Install dependencies
      #   run: npm ci

      # - name: Check formatting
      #   run: npm run format:check

      # - name: Run tests
      #   run: npm run test -- --coverage
      #   env:
      #     CI: true

      # - name: Print diff
      #   run: git log --pretty=format:%s origin/master..origin/fix-this
      #   env: 
      #     SHA: ${{ github.sha }}

      # - name: Send message to Slack \#general
      #   uses: "Ilshidur/action-slack@2.1.0"
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     VERSION: ${{ steps.get-next-version.outputs.new-release-version }}
      #     RELEASE_URL: ${{ format('https://github.com/{0}/releases/tag/v{1}', github.repository, steps.get-next-version.outputs.new-release-version) }}
      #     # RELEASE_URL: ${{ format('{0}{1}', 'https://github.com/yuliankarapetkov/react-cicd/releases/tag/v', steps.get-next-version.outputs.new-release-version) }}
      #     SLACK_CUSTOM_PAYLOAD: '{ "text": "Hello" }'
