name: CI
on:
  push:
    branches: [develop, master, fix-this]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "CI: ${CI}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_ENV: ${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_PATH: ${GITHUB_PATH}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF_PROTECTED: ${GITHUB_REF_PROTECTED}"
          echo "GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          echo "GITHUB_RETENTION_DAYS: ${GITHUB_RETENTION_DAYS}"
          echo "GITHUB_RUN_ATTEMPT: ${GITHUB_RUN_ATTEMPT}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_STEP_SUMMARY: ${GITHUB_STEP_SUMMARY}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "RUNNER_ARCH: ${RUNNER_ARCH}"
          echo "RUNNER_NAME: ${RUNNER_NAME}"
          echo "RUNNER_OS: ${RUNNER_OS}"
          echo "RUNNER_TEMP: ${RUNNER_TEMP}"
          echo "RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}"

      # - name: Checkout branch
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Print diff
      #   env: 
      #     SHA: ${{ github.sha }}
      #   run: |
      #     git log --pretty=format:%s origin/master..origin/${GITHUB_HEAD_REF}

      # - name: Setup Node version (16.x)
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "16.x"

      # - name: Install dependencies
      #   run: npm ci

      # - name: Check formatting
      #   run: npm run format:check

      # - name: Run tests
      #   run: npm run test -- --coverage
      #   env:
      #     CI: true

      # - name: Print diff
      #   run: git log --pretty=format:%s origin/master..origin/fix-this
      #   env: 
      #     SHA: ${{ github.sha }}

      # - name: Send message to Slack \#general
      #   uses: "Ilshidur/action-slack@2.1.0"
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     VERSION: ${{ steps.get-next-version.outputs.new-release-version }}
      #     RELEASE_URL: ${{ format('https://github.com/{0}/releases/tag/v{1}', github.repository, steps.get-next-version.outputs.new-release-version) }}
      #     # RELEASE_URL: ${{ format('{0}{1}', 'https://github.com/yuliankarapetkov/react-cicd/releases/tag/v', steps.get-next-version.outputs.new-release-version) }}
      #     SLACK_CUSTOM_PAYLOAD: '{ "text": "Hello" }'
