name: CI
on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node version (16.x)
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Check formatting
      #   run: npm run format:check
